### ISSUE TITLE
deal.getProduct only returns first 100 entries

### ISSUE THREAD

**Issue by rgraebert** [pipedrive/client-nodejs#19]
Hi,

I am using pipedrive.getAll to access organizations / products / persons > 100. However, the getXXX functions for related items (e.g. deals.getProducts) do not support pagination. Could you add a deal.getAll('Products') as well? I have a few deals I am trying to import with a large number of itemized sub items. 

Thanks

**Comment by martintajur** [comment]
Hi!

Right now, pagination actually does work for related items but it is not well documented.

It's a bit more complex than `deal.getAll('Products')` since there is yet no wrapper method for doing this, however I made a public example of how pagination does right now work and can be used:
https://github.com/pipedrive/client-nodejs/blob/master/examples/list-all-deal-products.js

You can contribute a `deal.getAll('Products')` interface proposal as a pull request if you wish to.

**Comment by rgraebert** [comment]
Thanks: I will take a look right away
