### ISSUE TITLE
Strict mode - Extra information

### ISSUE THREAD

**Issue by jessereitsma** [pipedrive/client-nodejs#45]
Hey there,

I just debugged the code like half a hour because the response from `Deals` doesn't had the "extended" version of (for example) `user_id`
When I did the same request in the browser, the response included the extended version of the id's.
After some debugging I noticed that in the library `strict_mode=1` is applied to the URI.
This causes to not include the extended objects for the id fields.

Though I understand it, it isn't very clear in the README. And I also couldn't find anything on strict_mode in the API documentation on developers.pipedrive.com

I'd like to see the README updated with some additional information about strict mode.
In the README it's just applied, without any comment on it.

Jesse

**Comment by martintajur** [comment]
@deespater We have to discuss this internally how to best handle it. Strict mode definitely is the proper way to handle things down the line but your team would know best what the plan is (or have a say in it).

**Comment by tot-ra** [comment]
Hey. I wanted to document both `strict_mode` and `related_objects` params in https://pipedrive.readme.io/docs

But now I think its good that this is a hidden feature (for performance of webapp), because we want to get rid of those. The plan is to have have graphql-like level support of what-you-ask is what-you-get. So until that happens, best to avoid encouraging usage of these params and thus not document it.
