### ISSUE TITLE
File upload breaks with binary files

### ISSUE THREAD

**Issue by scottsbaldwin** [pipedrive/client-nodejs#50]
When I use the JavaScript client to upload a binary file to a deal, the file gets corrupted. I see that issue #5 (which is closed) explains a fix was to use the `file_path` property. However, this only works for plain text files for me. When I use a binary file, I get the behavior that @alexandremaeda mentioned in #5.

Ultimately, I had to bypass using the JavaScript client completely and go straight to the API. I looked at how the Pipedrive web app did file uploads and saw that it used the `form-data` library. The gist below shows my solution using `form-data`. Because this solution deviates from the typical pattern in the JavaScript client for sending requests to the API, I did not create a pull request.

https://gist.github.com/scottsbaldwin/230465d8d90c9e05b37535dbc723c7ac

Could something like this be adapted to work in the API?

**Comment by HriBB** [comment]
@scottsbaldwin I am having the same issue. Thanks for the solution ;)

Would be nice if API supported uploading binary files though ...

**Comment by tot-ra** [comment]
I can confirm that uploading binary file (like image) through this library technically goes through, but result in UI is not viewable and compared to uploading same file through UI, they differ in filesize. Apparently the problem is in how data is embedded into multipart handler and how content-length is calculated

<img width="441" alt="screen shot 2018-03-31 at 19 45 34" src="https://user-images.githubusercontent.com/445122/38165446-34b6c096-351c-11e8-938a-80902a0d7049.png">

**Comment by celso** [comment]
I have this problem too. Any update?
