### ISSUE TITLE
Overwriting Axios interceptor cause issue to the application

### ISSUE THREAD

**Issue by AhmedBHameed** [pipedrive/client-nodejs#521]
Hello PipeDrive team,

We are integrating PipeDrive Node library with our project. We are encounter with an issue specifically with this version "[22.3.1-rc.4](https://www.npmjs.com/package/pipedrive/v/22.3.1-rc.4)".

After checking the internal code here https://github.com/pipedrive/client-nodejs/blob/v22.3.1-rc.4/base.ts, I noticed that you are overwriting the global axios interceptor causing by returning data rather than Axios Response object.

To fix that, you may need to instantiate a new axios instance and then apply the interceptor for the new instance. That will keep the original interceptor untouched.

We are using nest.js in our project.

**Comment by youssef-saber-3** [comment]
Hello @AhmedBHameed this issue has been fixed in this version https://www.npmjs.com/package/pipedrive/v/22.3.1-rc.5 thanks to @tz3 contribution here https://github.com/pipedrive/client-nodejs/pull/522. I'll close this github issue but feel free to comment or re-open it if you have any more problems with it
